import type { Metadata } from "next";
import {
  LegalPage,
  H2,
  H3,
  P,
  UL,
  OL,
  LI,
  Strong,
  Note,
  OperatorBlock,
} from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy: Leash",
  description: "How Leash handles personal data.",
  robots: { index: false, follow: false },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="May 23, 2026">
      <P>
        How Leash handles personal data. Short version: Leash is a non-custodial
        spend-governance layer for AI agents. It never holds your funds or
        private keys. We process your account data, the connection settings you
        configure for your own payment rails, the spending policies you define,
        and the audit logs Leash generates so you can see what your agents did.
      </P>

      <Note>
        <Strong>Operator note:</Strong> Leash is operated by HR Online
        Consulting LLC (DBA Leash) under the brand &ldquo;BrainBytes
        Studio.&rdquo; See Section 1.
      </Note>

      <H2>Table of Contents</H2>
      <OL>
        <LI>Controller (Operator)</LI>
        <LI>Overview of Processing</LI>
        <LI>Legal Bases for Processing</LI>
        <LI>Non-Custodial Architecture (What We Do NOT Process)</LI>
        <LI>Security Measures</LI>
        <LI>Transmission of Personal Data</LI>
        <LI>International Data Transfers</LI>
        <LI>Data Storage and Deletion</LI>
        <LI>Your Rights</LI>
        <LI>California Consumer Privacy Act (CCPA / CPRA) Disclosure</LI>
        <LI>Web Hosting (Vercel)</LI>
        <LI>Database (Managed Postgres)</LI>
        <LI>Authentication</LI>
        <LI>Payment Processing for Your Subscription (Stripe)</LI>
        <LI>Transactional Email (Resend)</LI>
        <LI>Web Analytics</LI>
        <LI>Connected Payment Rails (Lightning / Cashu / x402)</LI>
        <LI>Use of Cookies and Local Storage</LI>
        <LI>Do Not Track and Global Privacy Control</LI>
        <LI>Age Requirements</LI>
        <LI>Changes and Updates</LI>
        <LI>Definitions</LI>
        <LI>Contact</LI>
      </OL>

      <H2>1. Controller (Operator)</H2>
      <OperatorBlock />
      <P>
        HR Online Consulting LLC operates Leash under the brand
        &ldquo;BrainBytes Studio.&rdquo; The legal entity is a U.S. limited
        liability company with its principal office at the address above. There
        is no Data Protection Officer (DPO); questions about processing are
        answered directly at the email above.
      </P>

      <H2>2. Overview of Processing</H2>
      <H3>Categories of data processed</H3>
      <UL>
        <LI>
          <Strong>Anonymous visitors of the website:</Strong> log data (IP
          address, user-agent, timestamp, requested URL). Server logs only, no
          analytics cookies.
        </LI>
        <LI>
          <Strong>Registered users:</Strong> email address, name (optional),
          password hash, session tokens, account creation and update
          timestamps, role.
        </LI>
        <LI>
          <Strong>Workspace / organisation data:</Strong> workspace name,
          members, and the spending policies you define (budget caps, per-agent
          limits, allowed endpoints/mints, time windows, kill-switch state).
        </LI>
        <LI>
          <Strong>Agent identities:</Strong> the labels, scoped credentials, and
          policy bindings you create for each AI agent. These are governance
          metadata, not wallets.
        </LI>
        <LI>
          <Strong>Connection settings for your own payment rails:</Strong> the
          configuration you enter to let Leash enforce policy against your rails,
          for example a Lightning node connection URI / macaroon reference, an
          NWC connection string, a Cashu mint URL, or an x402 wallet endpoint.
          See Sections 4 and 17 for the strict non-custodial boundary.
        </LI>
        <LI>
          <Strong>Audit logs:</Strong> timestamped records of payment-governance
          events. Which agent requested a payment, to which endpoint, the
          amount, the rail, and the policy decision (allowed / denied / capped).
          Generated by Leash so you have a verifiable trail.
        </LI>
        <LI>
          <Strong>Paying users:</Strong> Stripe customer ID, subscription ID,
          plan, status, billing email, payment timestamps, invoice IDs. No card
          numbers; we never see or store them.
        </LI>
        <LI>
          <Strong>Anonymous usage analytics:</Strong> pageviews, referrer,
          country, device class. No cookies, no person-linkable identifiers.
        </LI>
      </UL>

      <H3>Categories of data subjects</H3>
      <UL>
        <LI>Visitors of leash.money (anonymous).</LI>
        <LI>Registered Leash users and their workspace members.</LI>
        <LI>Paying customers.</LI>
      </UL>

      <H3>Purposes of processing</H3>
      <UL>
        <LI>
          Provision of the spend-governance service (defining, enforcing, and
          auditing agent spending policies).
        </LI>
        <LI>Authentication and session management.</LI>
        <LI>Subscription billing and post-sale support.</LI>
        <LI>
          Generating and retaining audit logs so you can verify agent behaviour.
        </LI>
        <LI>Transactional email (account, billing, security notices).</LI>
        <LI>Aggregate usage analytics.</LI>
        <LI>Security, abuse prevention, and audit-log retention.</LI>
      </UL>

      <H2>3. Legal Bases for Processing</H2>
      <UL>
        <LI>
          <Strong>Contract (Art. 6(1)(b) GDPR / equivalent):</Strong> processing
          necessary to provide the service, charge for it, and operate your
          workspace.
        </LI>
        <LI>
          <Strong>Legitimate interests (Art. 6(1)(f) GDPR):</Strong> security,
          fraud prevention, server logs, IP-truncated aggregate analytics.
        </LI>
        <LI>
          <Strong>Consent (Art. 6(1)(a) GDPR):</Strong> we do not currently set
          any consent-requiring cookies. If we add an optional feature in the
          future, consent will be requested explicitly.
        </LI>
        <LI>
          <Strong>Statutory obligation:</Strong> retention of payment records for
          tax and accounting purposes per applicable U.S. law.
        </LI>
      </UL>

      <H2>4. Non-Custodial Architecture (What We Do NOT Process)</H2>
      <P>
        This is the most important section. <Strong>Leash is non-custodial
        software.</Strong>
      </P>
      <UL>
        <LI>
          We <Strong>never</Strong> take custody of your funds, your bitcoin,
          your sats, your stablecoins, or any balance.
        </LI>
        <LI>
          We <Strong>never</Strong> hold, generate, escrow, or have unilateral
          control over your private keys, seed phrases, or any equivalent
          security element. Where Leash enforces spending limits, it does so
          through scoped, revocable credentials and policy checks, not by
          controlling your keys.
        </LI>
        <LI>
          We are <Strong>not</Strong> a money transmitter, money services
          business, exchange, custodian, or financial intermediary. Leash does
          not move money on your behalf; it authorises or denies payment
          requests that your own connected rail then settles directly.
        </LI>
        <LI>
          Funds always flow between <Strong>your</Strong> connected
          wallet/node/mint and the counterparty endpoint. Leash sits in the
          policy path, not the custody path.
        </LI>
      </UL>
      <P>
        Practical consequence: even in a total compromise of Leash, an attacker
        cannot move your funds, because Leash never holds the keys that can.
      </P>

      <H2>5. Security Measures</H2>
      <UL>
        <LI>TLS/SSL encryption (HTTPS) for all data in transit.</LI>
        <LI>
          Password storage uses industry-standard one-way hashing; we cannot
          recover plaintext passwords.
        </LI>
        <LI>
          Connection secrets you provide (e.g. macaroon references, NWC strings)
          are encrypted at rest with envelope encryption; they are scoped to the
          minimum permission needed to enforce policy and are never logged in
          plaintext.
        </LI>
        <LI>Session tokens are short-lived and rotated.</LI>
        <LI>
          The database is hosted on private subnets with TLS to the application
          server.
        </LI>
        <LI>
          No card data is ever stored on our infrastructure; Stripe is the
          PCI-DSS-compliant processor.
        </LI>
        <LI>
          Access to production secrets is limited to the operator, via
          least-privilege scoped tokens.
        </LI>
      </UL>

      <H2>6. Transmission of Personal Data</H2>
      <P>
        We disclose personal data only to the processors listed in this Policy
        and only to the extent strictly necessary to provide the service. We do
        not sell personal data, and we do not share it for cross-context
        behavioural advertising.
      </P>
      <P>
        We may disclose data in response to a valid legal request (court order,
        subpoena) when compelled by U.S. law. If we receive such a request and
        the law does not prohibit it, we will notify the affected user.
      </P>

      <H2>7. International Data Transfers</H2>
      <P>
        Our operator is U.S.-based. Personal data is processed in the U.S. and
        in any region our service providers operate. For transfers from the
        EU/EEA/UK to the U.S., we rely on the <Strong>EU-U.S. Data Privacy
        Framework (DPF)</Strong> and, as a safeguard, <Strong>Standard
        Contractual Clauses</Strong> with our service providers. For each
        provider listed below we indicate the transfer basis.
      </P>

      <H2>8. Data Storage and Deletion</H2>
      <UL>
        <LI>
          <Strong>Server logs:</Strong> retained 30 days, then deleted or
          anonymised.
        </LI>
        <LI>
          <Strong>Account &amp; workspace records:</Strong> retained for the life
          of the account. Deleted within 30 days of an account-deletion request.
        </LI>
        <LI>
          <Strong>Spending policies &amp; agent identities:</Strong> retained
          while the workspace exists; deleted when removed or when the account is
          deleted.
        </LI>
        <LI>
          <Strong>Connection secrets:</Strong> deleted immediately when you
          disconnect a rail or delete the account.
        </LI>
        <LI>
          <Strong>Audit logs:</Strong> retained for the life of the workspace
          (you can export them anytime). You can request earlier deletion,
          subject to fraud-prevention and statutory exceptions.
        </LI>
        <LI>
          <Strong>Stripe billing data:</Strong> retained as long as required by
          tax and accounting law, typically seven (7) years.
        </LI>
      </UL>

      <H2>9. Your Rights</H2>
      <P>
        You have the rights of access, rectification, erasure, restriction,
        portability, objection, and withdrawal of consent, and the right to
        lodge a complaint with your supervisory authority. To exercise any
        right, email{" "}
        <a
          href="mailto:support@leash.money"
          className="text-primary hover:underline"
        >
          support@leash.money
        </a>
        . We respond within 30 days; complex requests may be extended by an
        additional 60 days with notice.
      </P>

      <H2>10. California Consumer Privacy Act (CCPA / CPRA) Disclosure</H2>
      <P>
        If you are a California resident, the CCPA as amended by the CPRA grants
        you specific rights, supplementing Section 9.
      </P>
      <UL>
        <LI>
          <Strong>Categories collected:</Strong> identifiers (email, account ID,
          IP), customer records (billing email), commercial information
          (subscription tier), internet activity (aggregate analytics),
          approximate IP-derived geolocation. <Strong>Inferences: none</Strong>,
          we build no behavioural profiles.
        </LI>
        <LI>
          <Strong>We do not collect:</Strong> SSNs, financial-account numbers,
          biometric, health, education, or employment data.
        </LI>
        <LI>
          <Strong>Sources:</Strong> directly from you; from your browser; from
          Stripe on payment events.
        </LI>
        <LI>
          <Strong>Sale / sharing:</Strong> we do <Strong>not</Strong> sell
          personal information and do <Strong>not</Strong> share it for
          cross-context behavioural advertising.
        </LI>
        <LI>
          <Strong>Sensitive personal information:</Strong> none collected.
        </LI>
        <LI>
          <Strong>Your rights:</Strong> to know, delete, correct, opt out of
          sale/sharing (already the default), and non-discrimination. Email{" "}
          <a
            href="mailto:support@leash.money"
            className="text-primary hover:underline"
          >
            support@leash.money
          </a>{" "}
          with subject &ldquo;California Privacy Request.&rdquo; We respond
          within 45 days.
        </LI>
      </UL>

      <H2>11. Web Hosting (Vercel)</H2>
      <P>
        The Service is hosted on Vercel. Provider: Vercel Inc., 440 N Barranca
        Ave #4133, Covina, CA 91723, USA. Privacy policy:
        vercel.com/legal/privacy-policy. Transfer basis: <Strong>DPF
        certified</Strong>. Vercel processes server log files to deliver the
        Service and detect abuse; retention up to 30 days.
      </P>

      <H2>12. Database (Managed Postgres)</H2>
      <P>
        Account records, workspace data, spending policies, agent identities,
        encrypted connection secrets, and audit logs are stored in a managed
        Postgres database. Provider details and privacy policy are published on
        our website and kept current; transfer basis is Standard Contractual
        Clauses.
      </P>

      <H2>13. Authentication</H2>
      <P>
        Authentication runs inside our own server using an open-source library.
        Password hashes, session tokens, and verification records stay in our
        database. The session cookie is first-party, HttpOnly, Secure, and
        SameSite=Lax. Magic-link sign-in (if enabled) uses a single-use 15-minute
        token, stored hashed and invalidated on first use.
      </P>

      <H2>14. Payment Processing for Your Subscription (Stripe)</H2>
      <P>
        Your <Strong>subscription to Leash</Strong> is billed by Stripe.
        Provider: Stripe, Inc., 354 Oyster Point Blvd, South San Francisco, CA
        94080, USA. Privacy policy: stripe.com/privacy. Transfer basis:{" "}
        <Strong>DPF certified</Strong>. When you check out you are redirected to
        a Stripe-operated domain; Stripe processes payment data there under its
        own policy. We never receive card numbers. On success, Stripe sends a
        webhook (customer ID, subscription ID, billing email, plan, status,
        invoice IDs) which we use to set your subscription state and email your
        receipt.
      </P>
      <P>
        This is entirely separate from the payments your <Strong>agents</Strong>{" "}
        make over your connected rails (Section 17), which never touch Leash&apos;s
        infrastructure or balance.
      </P>

      <H2>15. Transactional Email (Resend)</H2>
      <P>
        We use Resend to deliver account, billing, and security emails. Sender
        domain is leash.money, verified with SPF and DKIM. Provider: Resend,
        Inc., 2261 Market Street #4667, San Francisco, CA 94114, USA. Privacy
        policy: resend.com/legal/privacy-policy. Transfer basis: Standard
        Contractual Clauses. Only your email address, name (if provided), and
        the message body are sent to Resend.
      </P>

      <H2>16. Web Analytics</H2>
      <P>
        We use a cookieless, first-party analytics service that records
        pageviews, referrer, country (IP-derived), and a coarse device class. No
        client-side identifiers are stored. We do <Strong>not</Strong> use
        Google Analytics, Tag Manager, Facebook/TikTok/X/LinkedIn pixels, or any
        third-party tracking script.
      </P>

      <H2>17. Connected Payment Rails (Lightning / Cashu / x402)</H2>
      <P>
        When you connect a payment rail so Leash can enforce policy, the
        following applies:
      </P>
      <UL>
        <LI>
          You provide connection settings (e.g. a Lightning node URI with a{" "}
          <Strong>scoped, spend-limited</Strong> macaroon, an NWC connection
          string, a Cashu mint URL, or an x402 wallet endpoint). These are
          encrypted at rest (Section 5).
        </LI>
        <LI>
          Leash uses these <Strong>only</Strong> to (a) read the state needed for
          policy decisions and (b) authorise or deny a payment request according
          to your policy. Settlement happens on your rail, between your
          wallet/node/mint and the counterparty.
        </LI>
        <LI>
          Leash never receives, holds, or routes your funds. See Section 4.
        </LI>
        <LI>
          We recommend connecting credentials that are themselves scoped (e.g.
          macaroons restricted to the minimum permissions, NWC budgets) so that
          the credential&apos;s own limits reinforce Leash&apos;s policy. Defence in
          depth.
        </LI>
      </UL>

      <H2>18. Use of Cookies and Local Storage</H2>
      <P>
        We use first-party storage only: a necessary <code>session_token</code>{" "}
        cookie (HttpOnly, Secure) for your authenticated session, and a{" "}
        <code>leash-theme</code> localStorage entry for your light/dark
        preference. We set no third-party cookies. Stripe cookies, when present,
        are set by Stripe on its own checkout domain, not on leash.money.
      </P>

      <H2>19. Do Not Track and Global Privacy Control</H2>
      <P>
        We respect the <code>Sec-GPC: 1</code> Global Privacy Control header and
        the legacy <code>DNT: 1</code> header. Because we do not engage in
        cross-context behavioural advertising, the signal has no behaviour to
        suppress, but we treat it as a standing opt-out and document it for
        auditability.
      </P>

      <H2>20. Age Requirements</H2>
      <P>
        Leash is a developer tool not directed to children. Creating an account
        requires you to be at least 18 years old, in line with our payment
        processor&apos;s terms. We do not knowingly collect personal information
        from children under 13 (COPPA threshold). If a parent or guardian
        believes we have, email{" "}
        <a
          href="mailto:support@leash.money"
          className="text-primary hover:underline"
        >
          support@leash.money
        </a>{" "}
        and we will delete it promptly.
      </P>

      <H2>21. Changes and Updates</H2>
      <P>
        We update this Policy as the service evolves. The &ldquo;Last
        updated&rdquo; date reflects the most recent substantive change. For
        material changes affecting your rights, we notify registered users by
        email and surface an in-product notice.
      </P>

      <H2>22. Definitions</H2>
      <UL>
        <LI>
          <Strong>Personal data:</Strong> any information relating to an
          identified or identifiable natural person.
        </LI>
        <LI>
          <Strong>Controller (operator):</Strong> the entity that determines the
          purposes and means of processing, here, HR Online Consulting LLC.
        </LI>
        <LI>
          <Strong>Processor:</Strong> a third party that processes personal data
          on behalf of the controller (Vercel, the database provider, Stripe,
          Resend).
        </LI>
        <LI>
          <Strong>Non-custodial:</Strong> an architecture in which the operator
          never holds or controls the user&apos;s funds or private keys.
        </LI>
        <LI>
          <Strong>Audit log:</Strong> a timestamped record Leash generates of
          agent payment-governance events.
        </LI>
        <LI>
          <Strong>Sale / Sharing (CCPA):</Strong> exchange or
          cross-context-advertising disclosure of personal information, we do
          neither.
        </LI>
      </UL>

      <H2>23. Contact</H2>
      <P>
        For any privacy question, or to exercise any right described above:
      </P>
      <OperatorBlock />
    </LegalPage>
  );
}
